// Auto-generated by: supabase gen types typescript --linked
// Regenerate after schema changes: npm run db:types
//
// TODO: Replace this placeholder once schema is deployed to STG.
// Run: npm run db:types
//
// This permissive placeholder allows Supabase client calls to compile
// before real types are generated. All table/column names are unchecked
// until the real types replace this file.

/* eslint-disable @typescript-eslint/no-explicit-any */
type AnyTable = {
  Row: Record<string, any>
  Insert: Record<string, any>
  Update: Record<string, any>
  Relationships: any[]
}

export type Database = {
  public: {
    Tables: Record<string, AnyTable>
    Views: Record<string, AnyTable>
    Functions: Record<string, { Args: Record<string, any>; Returns: any }>
    Enums: Record<string, string>
    CompositeTypes: Record<string, any>
  }
}
/* eslint-enable @typescript-eslint/no-explicit-any */
