// Auto-generated by: supabase gen types typescript --linked
// Regenerate after schema changes: npm run db:types
//
// Placeholder until schema is deployed (FND-DB-001).
// This will be replaced with the full generated types.

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
