import { beforeEach, describe, expect, test, vi } from 'vitest'

// ---------------------------------------------------------------------------
// Mocks
// ---------------------------------------------------------------------------

vi.mock('server-only', () => ({}))

const mockSignOut = vi.fn()
const mockSignInWithOtp = vi.fn()
const mockGetUser = vi.fn()
const mockUpdate = vi.fn()
const mockEq = vi.fn()
const mockSelect = vi.fn()
const mockSelectEq = vi.fn()
const mockSingle = vi.fn()
const mockDelete = vi.fn()
const mockSet = vi.fn()
const mockTrackEvent = vi.fn()
const mockCaptureServerError = vi.fn()

vi.mock('@/lib/supabase/server', () => ({
  createServerClient: vi.fn().mockResolvedValue({
    auth: {
      signOut: (...args: unknown[]) => mockSignOut(...args),
      signInWithOtp: (...args: unknown[]) => mockSignInWithOtp(...args),
      getUser: (...args: unknown[]) => mockGetUser(...args),
    },
    from: () => ({
      update: (...args: unknown[]) => {
        mockUpdate(...args)
        return { eq: (...eqArgs: unknown[]) => mockEq(...eqArgs) }
      },
      select: (...args: unknown[]) => {
        mockSelect(...args)
        return {
          eq: (...eqArgs: unknown[]) => {
            mockSelectEq(...eqArgs)
            return { single: () => mockSingle() }
          },
        }
      },
    }),
  }),
}))

vi.mock('next/headers', () => ({
  cookies: vi.fn().mockResolvedValue({
    delete: (...args: unknown[]) => mockDelete(...args),
    set: (...args: unknown[]) => mockSet(...args),
  }),
}))

vi.mock('next/navigation', () => ({
  redirect: vi.fn((url: string) => {
    throw new RedirectError(url)
  }),
}))

vi.mock('@/lib/analytics/server', () => ({
  trackEvent: (...args: unknown[]) => mockTrackEvent(...args),
  captureServerError: (...args: unknown[]) => mockCaptureServerError(...args),
}))

/**
 * Records each `withTiming` invocation as `[actionName, userId]`. Tests
 * use this to assert SERVER_ACTION_DURATION coverage WITHOUT polluting
 * the `mockTrackEvent` spy that the rest of the suite asserts on.
 */
const mockDurationFires: Array<[string, string]> = []

const mockWithTiming = vi.fn(
  async <T,>(actionName: string, userId: string, fn: () => Promise<T>): Promise<T> => {
    try {
      return await fn()
    } finally {
      // R-016: record the duration "fire" so we can prove the wrapper
      // actually ran around the action. This matches the real
      // `withTiming` behaviour: the duration event fires regardless of
      // success or failure, and analytics errors must never mask the
      // original throw.
      try {
        mockDurationFires.push([actionName, userId])
      } catch {
        // Never mask the original throw
      }
    }
  },
)

// withTiming wraps the action in tests too — we mirror the real
// SERVER_ACTION_DURATION fire so test assertions can verify the wrapper
// is wired up correctly.
vi.mock('@/lib/analytics/timing', () => ({
  withTiming: (...args: unknown[]) =>
    mockWithTiming(
      args[0] as string,
      args[1] as string,
      args[2] as () => Promise<unknown>,
    ),
}))

vi.mock('@/lib/env', () => ({
  env: {
    NEXT_PUBLIC_APP_URL: 'https://bragg.app',
  },
}))

/** Sentinel error thrown by the mocked `redirect()` to simulate Next.js behaviour. */
class RedirectError extends Error {
  url: string
  constructor(url: string) {
    super(`NEXT_REDIRECT: ${url}`)
    this.url = url
  }
}

// Import after mocks are set up
const { signOut, sendMagicLink, completeOnboarding, acceptTerms } = await import('./auth')

// Reset the duration-fire log between every test so per-action assertions
// only see the fires generated by the current test.
beforeEach(() => {
  mockDurationFires.length = 0
})

// ---------------------------------------------------------------------------
// signOut
// ---------------------------------------------------------------------------

describe('signOut server action', () => {
  const mockUser = { id: 'user-456' }

  beforeEach(() => {
    vi.clearAllMocks()
    mockSignOut.mockResolvedValue({ error: null })
    mockGetUser.mockResolvedValue({ data: { user: mockUser }, error: null })
  })

  test('signs out, clears cookies, fires analytics, and redirects to /', async () => {
    const error = await signOut().catch((e: unknown) => e) as RedirectError

    expect(error).toBeInstanceOf(RedirectError)
    expect(error.url).toBe('/')
    expect(mockSignOut).toHaveBeenCalledOnce()
    expect(mockDelete).toHaveBeenCalledWith('bragg_onboarded')
    expect(mockDelete).toHaveBeenCalledWith('bragg_terms_version')
    expect(mockTrackEvent).toHaveBeenCalledWith('user-456', 'signed_out')
    // Wrapped in withTiming with the camelCase action name and the resolved user id
    expect(mockWithTiming).toHaveBeenCalledWith(
      'signOut',
      'user-456',
      expect.any(Function),
    )
  })

  test('signs out without analytics when getUser returns no user', async () => {
    mockGetUser.mockResolvedValue({ data: { user: null }, error: null })

    const error = await signOut().catch((e: unknown) => e) as RedirectError

    expect(error).toBeInstanceOf(RedirectError)
    expect(error.url).toBe('/')
    expect(mockSignOut).toHaveBeenCalledOnce()
    expect(mockDelete).toHaveBeenCalledWith('bragg_onboarded')
    expect(mockDelete).toHaveBeenCalledWith('bragg_terms_version')
    expect(mockTrackEvent).not.toHaveBeenCalled()
  })

  test('returns error when supabase signOut fails', async () => {
    mockSignOut.mockResolvedValue({
      error: { message: 'session_not_found' },
    })

    const result = await signOut()

    expect(result).toEqual({ success: false, error: 'session_not_found' })
    // Cookies should NOT be deleted when signOut itself fails
    expect(mockDelete).not.toHaveBeenCalled()
    expect(mockTrackEvent).not.toHaveBeenCalled()
    // Failure path captures the error to PostHog with the action source
    expect(mockCaptureServerError).toHaveBeenCalledWith(
      'user-456',
      expect.objectContaining({ message: 'session_not_found' }),
      expect.objectContaining({ source: 'signOut' }),
    )
  })

  test('returns generic error when an unexpected exception is thrown', async () => {
    mockSignOut.mockRejectedValue(new Error('network failure'))

    const result = await signOut()

    expect(result).toEqual({
      success: false,
      error: 'Failed to sign out. Please try again.',
    })
    expect(mockDelete).not.toHaveBeenCalled()
    expect(mockTrackEvent).not.toHaveBeenCalled()
  })
})

// ---------------------------------------------------------------------------
// sendMagicLink
// ---------------------------------------------------------------------------

describe('sendMagicLink server action', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockSignInWithOtp.mockResolvedValue({ error: null })
  })

  test('returns success for a valid email', async () => {
    const result = await sendMagicLink('user@example.com')

    expect(result).toEqual({ success: true })
    expect(mockSignInWithOtp).toHaveBeenCalledOnce()
    expect(mockSignInWithOtp).toHaveBeenCalledWith({
      email: 'user@example.com',
      options: {
        emailRedirectTo: 'https://bragg.app/auth/callback',
      },
    })
  })

  test('constructs callback URL with redirectTo when provided', async () => {
    const result = await sendMagicLink('user@example.com', '/dashboard')

    expect(result).toEqual({ success: true })
    expect(mockSignInWithOtp).toHaveBeenCalledWith({
      email: 'user@example.com',
      options: {
        emailRedirectTo: 'https://bragg.app/auth/callback?redirectTo=%2Fdashboard',
      },
    })
  })

  test('sanitizes protocol-relative redirectTo to prevent open redirect', async () => {
    const result = await sendMagicLink('user@example.com', '//evil.com')

    expect(result).toEqual({ success: true })
    expect(mockSignInWithOtp).toHaveBeenCalledWith({
      email: 'user@example.com',
      options: {
        emailRedirectTo: 'https://bragg.app/auth/callback?redirectTo=%2Fdashboard',
      },
    })
  })

  test('sanitizes absolute URL redirectTo to prevent open redirect', async () => {
    const result = await sendMagicLink('user@example.com', 'https://evil.com')

    expect(result).toEqual({ success: true })
    expect(mockSignInWithOtp).toHaveBeenCalledWith({
      email: 'user@example.com',
      options: {
        emailRedirectTo: 'https://bragg.app/auth/callback?redirectTo=%2Fdashboard',
      },
    })
  })

  test('sanitizes backslash-based redirectTo to prevent open redirect', async () => {
    const result = await sendMagicLink('user@example.com', '/\\evil.com')

    expect(result).toEqual({ success: true })
    expect(mockSignInWithOtp).toHaveBeenCalledWith({
      email: 'user@example.com',
      options: {
        emailRedirectTo: 'https://bragg.app/auth/callback?redirectTo=%2Fdashboard',
      },
    })
  })

  test('returns validation error for empty email', async () => {
    const result = await sendMagicLink('')

    expect(result).toEqual({ success: false, error: 'Email is required' })
    expect(mockSignInWithOtp).not.toHaveBeenCalled()
  })

  test('returns validation error for invalid email format', async () => {
    const result = await sendMagicLink('not-an-email')

    expect(result).toEqual({ success: false, error: 'Please enter a valid email address' })
    expect(mockSignInWithOtp).not.toHaveBeenCalled()
  })

  test('returns rate limit error when Supabase returns 429', async () => {
    mockSignInWithOtp.mockResolvedValue({
      error: { status: 429, message: 'Rate limit exceeded' },
    })

    const result = await sendMagicLink('user@example.com')

    expect(result).toEqual({
      success: false,
      error: 'Too many attempts. Please try again later.',
    })
  })

  test('returns generic error for other Supabase errors', async () => {
    mockSignInWithOtp.mockResolvedValue({
      error: { status: 500, message: 'Internal server error' },
    })

    const result = await sendMagicLink('user@example.com')

    expect(result).toEqual({
      success: false,
      error: 'Failed to send magic link. Please try again.',
    })
    expect(mockCaptureServerError).toHaveBeenCalledWith(
      expect.any(String),
      expect.objectContaining({ status: 500 }),
      expect.objectContaining({ source: 'sendMagicLink' }),
    )
  })

  test('fires MAGIC_LINK_REQUESTED analytics event on success', async () => {
    await sendMagicLink('user@example.com')

    expect(mockTrackEvent).toHaveBeenCalledOnce()
    // The pseudo-userId IS the hashed email — passing it as a property
    // would just duplicate the distinctId, so the event fires with no
    // properties at all. Asserting `email_hash` is absent locks in the
    // R-009 fix.
    expect(mockTrackEvent).toHaveBeenCalledWith(
      expect.any(String),
      'magic_link_requested',
    )
    const [, , props] = mockTrackEvent.mock.calls[0] ?? []
    expect(props).toBeUndefined()
    // Wrapped in withTiming with the camelCase action name + hashed pseudo-user id
    expect(mockWithTiming).toHaveBeenCalledWith(
      'sendMagicLink',
      expect.any(String),
      expect.any(Function),
    )
  })

  test('does not fire analytics event on validation error', async () => {
    await sendMagicLink('not-an-email')

    expect(mockTrackEvent).not.toHaveBeenCalled()
  })

  test('does not fire analytics event on Supabase error', async () => {
    mockSignInWithOtp.mockResolvedValue({
      error: { status: 500, message: 'Internal server error' },
    })

    await sendMagicLink('user@example.com')

    expect(mockTrackEvent).not.toHaveBeenCalled()
  })
})

// ---------------------------------------------------------------------------
// completeOnboarding
// ---------------------------------------------------------------------------

describe('completeOnboarding server action', () => {
  const validData = {
    displayName: 'Test User',
    dateOfBirth: '1990-05-15',
    termsAccepted: true as const,
  }

  const mockUser = { id: 'user-123' }

  beforeEach(() => {
    vi.clearAllMocks()
    mockGetUser.mockResolvedValue({ data: { user: mockUser }, error: null })
    mockSingle.mockResolvedValue({ data: { onboarding_completed: false }, error: null })
    mockEq.mockResolvedValue({ error: null })
  })

  test('updates profile, sets cookies, fires analytics, and redirects on valid data', async () => {
    const error = await completeOnboarding(validData).catch((e: unknown) => e) as RedirectError

    expect(error).toBeInstanceOf(RedirectError)
    expect(error.url).toBe('/dashboard')

    // Profile update
    expect(mockUpdate).toHaveBeenCalledOnce()
    expect(mockUpdate).toHaveBeenCalledWith(
      expect.objectContaining({
        display_name: 'Test User',
        date_of_birth: '1990-05-15',
        terms_version: '2.0',
        onboarding_completed: true,
      }),
    )
    expect(mockEq).toHaveBeenCalledWith('id', 'user-123')

    // Cookies
    expect(mockSet).toHaveBeenCalledWith('bragg_onboarded', 'true', expect.objectContaining({
      httpOnly: true,
      sameSite: 'lax',
      maxAge: 365 * 24 * 60 * 60,
      path: '/',
    }))
    expect(mockSet).toHaveBeenCalledWith('bragg_terms_version', '2.0', expect.objectContaining({
      httpOnly: true,
      sameSite: 'lax',
      maxAge: 365 * 24 * 60 * 60,
      path: '/',
    }))

    // Analytics — display_name must NOT be sent as a property (R-006). The
    // distinctId is enough to look the name up later if needed.
    expect(mockTrackEvent).toHaveBeenCalledWith('user-123', 'onboarding_completed')
    const onboardingCall = mockTrackEvent.mock.calls.find(
      (call) => call[1] === 'onboarding_completed',
    )
    expect(onboardingCall?.[2]).toBeUndefined()

    // R-016: prove the action body actually ran INSIDE `withTiming`. The
    // duration log fires for every wrapped action — if a regression moved
    // the body outside the wrapper this assertion would fail.
    expect(mockDurationFires).toContainEqual(['completeOnboarding', 'user-123'])
  })

  test('redirects to custom redirectTo when provided', async () => {
    const error = await completeOnboarding(validData, '/groups').catch(
      (e: unknown) => e,
    ) as RedirectError

    expect(error).toBeInstanceOf(RedirectError)
    expect(error.url).toBe('/groups')
  })

  test('returns error when user is not authenticated', async () => {
    mockGetUser.mockResolvedValue({ data: { user: null }, error: null })

    const result = await completeOnboarding(validData)

    expect(result).toEqual({
      success: false,
      error: 'You must be logged in to complete onboarding.',
    })
    expect(mockUpdate).not.toHaveBeenCalled()
  })

  test('returns error when auth check fails', async () => {
    mockGetUser.mockResolvedValue({
      data: { user: null },
      error: { message: 'session expired' },
    })

    const result = await completeOnboarding(validData)

    expect(result).toEqual({
      success: false,
      error: 'You must be logged in to complete onboarding.',
    })
  })

  test('returns error when user has already completed onboarding', async () => {
    mockSingle.mockResolvedValue({ data: { onboarding_completed: true }, error: null })

    const result = await completeOnboarding(validData)

    expect(result).toEqual({
      success: false,
      error: 'Onboarding already completed.',
    })
    expect(mockUpdate).not.toHaveBeenCalled()
    expect(mockSet).not.toHaveBeenCalled()
    expect(mockTrackEvent).not.toHaveBeenCalled()
  })

  test('returns validation error for short display name', async () => {
    const result = await completeOnboarding({
      ...validData,
      displayName: 'A',
    })

    expect(result).toEqual({
      success: false,
      error: 'Display name must be at least 2 characters',
    })
    expect(mockUpdate).not.toHaveBeenCalled()
  })

  test('returns validation error for long display name', async () => {
    const result = await completeOnboarding({
      ...validData,
      displayName: 'A'.repeat(31),
    })

    expect(result).toEqual({
      success: false,
      error: 'Display name must be at most 30 characters',
    })
  })

  test('returns validation error for underage user', async () => {
    const today = new Date()
    const underageDate = `${today.getFullYear() - 17}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`

    const result = await completeOnboarding({
      ...validData,
      dateOfBirth: underageDate,
    })

    expect(result).toEqual({
      success: false,
      error: 'You must be 18 or older to use Bragg',
    })
    expect(mockUpdate).not.toHaveBeenCalled()
  })

  test('returns validation error when terms not accepted', async () => {
    const result = await completeOnboarding({
      displayName: 'Test User',
      dateOfBirth: '1990-05-15',
      termsAccepted: false,
    })

    expect(result).toEqual({
      success: false,
      error: 'You must accept the Terms of Service and Privacy Policy',
    })
    expect(mockUpdate).not.toHaveBeenCalled()
  })

  test('returns error when profile update fails', async () => {
    mockEq.mockResolvedValue({ error: { message: 'db error' } })

    const result = await completeOnboarding(validData)

    expect(result).toEqual({
      success: false,
      error: 'Failed to save your profile. Please try again.',
    })
    // Cookies should NOT be set when update fails
    expect(mockSet).not.toHaveBeenCalled()
  })

  test('trims display name whitespace', async () => {
    const error = await completeOnboarding({
      ...validData,
      displayName: '  Test User  ',
    }).catch((e: unknown) => e) as RedirectError

    expect(error).toBeInstanceOf(RedirectError)
    expect(mockUpdate).toHaveBeenCalledWith(
      expect.objectContaining({
        display_name: 'Test User',
      }),
    )
  })

  test('does not fire analytics when auth fails', async () => {
    mockGetUser.mockResolvedValue({ data: { user: null }, error: null })

    await completeOnboarding(validData)

    expect(mockTrackEvent).not.toHaveBeenCalled()
  })
})

// ---------------------------------------------------------------------------
// acceptTerms
// ---------------------------------------------------------------------------

describe('acceptTerms server action', () => {
  const mockUser = { id: 'user-789' }

  beforeEach(() => {
    vi.clearAllMocks()
    mockGetUser.mockResolvedValue({ data: { user: mockUser }, error: null })
    mockEq.mockResolvedValue({ error: null })
  })

  test('returns error when user is not authenticated', async () => {
    mockGetUser.mockResolvedValue({ data: { user: null }, error: null })

    const result = await acceptTerms()

    expect(result).toEqual({
      success: false,
      error: 'You must be logged in to accept terms.',
    })
    expect(mockUpdate).not.toHaveBeenCalled()
    expect(mockSet).not.toHaveBeenCalled()
    expect(mockTrackEvent).not.toHaveBeenCalled()
  })

  test('returns error when auth check fails', async () => {
    mockGetUser.mockResolvedValue({
      data: { user: null },
      error: { message: 'session expired' },
    })

    const result = await acceptTerms()

    expect(result).toEqual({
      success: false,
      error: 'You must be logged in to accept terms.',
    })
    expect(mockUpdate).not.toHaveBeenCalled()
  })

  test('updates profile, sets cookie, fires analytics, and redirects on success', async () => {
    const error = await acceptTerms().catch((e: unknown) => e) as RedirectError

    expect(error).toBeInstanceOf(RedirectError)
    expect(error.url).toBe('/dashboard')

    // Profile update
    expect(mockUpdate).toHaveBeenCalledOnce()
    expect(mockUpdate).toHaveBeenCalledWith(
      expect.objectContaining({
        terms_version: '2.0',
        terms_accepted_at: expect.any(String),
      }),
    )
    expect(mockEq).toHaveBeenCalledWith('id', 'user-789')

    // Cookie
    expect(mockSet).toHaveBeenCalledWith('bragg_terms_version', '2.0', expect.objectContaining({
      httpOnly: true,
      sameSite: 'lax',
      maxAge: 365 * 24 * 60 * 60,
      path: '/',
    }))

    // Analytics
    expect(mockTrackEvent).toHaveBeenCalledWith('user-789', 'terms_accepted')
  })

  test('returns error when profile update fails', async () => {
    mockEq.mockResolvedValue({ error: { message: 'db error' } })

    const result = await acceptTerms()

    expect(result).toEqual({
      success: false,
      error: 'Failed to accept terms. Please try again.',
    })
    // Cookie should NOT be set when update fails
    expect(mockSet).not.toHaveBeenCalled()
    // Analytics should NOT fire when update fails
    expect(mockTrackEvent).not.toHaveBeenCalled()
  })
})
